### ISSUE TITLE
No AV.gif present in the Forensics Writeup

### ISSUE THREAD

**Issue by thisisthedarshan** [KLSGIT-WGCS/VishwaCTF-2023#2]
There is no file present in the [Guatemala](http://klsgit-wgcs.github.io/VishwaCTF-2023/writeups/Steganography/Guatemala) Writeup.

@mirai-cmd - Add the file.

Also, it is suggested that you move the files to a separate folder (Like for Forensics, move the files database.db & image.jpg to _Forensics/assets/OakTownMystery/_).

Another suggestion, use a specific name for the files such as TrafficDatabaseRecords.db & SecurityCam.jpg. (_Just a suggestion!_)

Take the necessary actions and close the issue :)

If @Nightowl-code is ready, he can do the same.
# 

_頑張ってね!_ :D

**Comment by mirai-cmd** [comment]
Cool I'll make the changes. Will inform @Nightowl-code to do the same.

**Comment by mirai-cmd** [comment]
Changes made. Just review them once.

**Comment by mirai-cmd** [comment]
I'm closing the issue
